// Code generated by MockGen. DO NOT EDIT.
// Source: internal/rabbitmq/producer.go
//
// Generated by this command:
//
//	mockgen -source=internal/rabbitmq/producer.go -destination=internal/rabbitmq/mocks/mock_producer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
