// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source=server.go -destination=../service/mocks/mock_service.go -package=mocks ServiceDelayedNotifierInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "DelayedNotifier/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceDelayedNotifierInterface is a mock of ServiceDelayedNotifierInterface interface.
type MockServiceDelayedNotifierInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceDelayedNotifierInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceDelayedNotifierInterfaceMockRecorder is the mock recorder for MockServiceDelayedNotifierInterface.
type MockServiceDelayedNotifierInterfaceMockRecorder struct {
	mock *MockServiceDelayedNotifierInterface
}

// NewMockServiceDelayedNotifierInterface creates a new mock instance.
func NewMockServiceDelayedNotifierInterface(ctrl *gomock.Controller) *MockServiceDelayedNotifierInterface {
	mock := &MockServiceDelayedNotifierInterface{ctrl: ctrl}
	mock.recorder = &MockServiceDelayedNotifierInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceDelayedNotifierInterface) EXPECT() *MockServiceDelayedNotifierInterfaceMockRecorder {
	return m.recorder
}

// CreateNotification mocks base method.
func (m *MockServiceDelayedNotifierInterface) CreateNotification(arg0 *models.Notification) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockServiceDelayedNotifierInterfaceMockRecorder) CreateNotification(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockServiceDelayedNotifierInterface)(nil).CreateNotification), arg0)
}

// DeleteNotification mocks base method.
func (m *MockServiceDelayedNotifierInterface) DeleteNotification(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotification", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotification indicates an expected call of DeleteNotification.
func (mr *MockServiceDelayedNotifierInterfaceMockRecorder) DeleteNotification(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotification", reflect.TypeOf((*MockServiceDelayedNotifierInterface)(nil).DeleteNotification), id)
}

// GetAllNotifications mocks base method.
func (m *MockServiceDelayedNotifierInterface) GetAllNotifications() ([]*models.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotifications")
	ret0, _ := ret[0].([]*models.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotifications indicates an expected call of GetAllNotifications.
func (mr *MockServiceDelayedNotifierInterfaceMockRecorder) GetAllNotifications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotifications", reflect.TypeOf((*MockServiceDelayedNotifierInterface)(nil).GetAllNotifications))
}

// GetNotificationStatus mocks base method.
func (m *MockServiceDelayedNotifierInterface) GetNotificationStatus(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationStatus", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationStatus indicates an expected call of GetNotificationStatus.
func (mr *MockServiceDelayedNotifierInterfaceMockRecorder) GetNotificationStatus(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationStatus", reflect.TypeOf((*MockServiceDelayedNotifierInterface)(nil).GetNotificationStatus), id)
}

// ProcessNotification mocks base method.
func (m *MockServiceDelayedNotifierInterface) ProcessNotification(nf *models.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNotification", nf)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessNotification indicates an expected call of ProcessNotification.
func (mr *MockServiceDelayedNotifierInterfaceMockRecorder) ProcessNotification(nf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNotification", reflect.TypeOf((*MockServiceDelayedNotifierInterface)(nil).ProcessNotification), nf)
}
